version: '3.9'
services:
  bilibili_tool:
    image: ghcr.io/raywangqvq/bilibili_tool_pro
    container_name: bili
    restart: unless-stopped
    tty: true
    volumes:
      - ./Logs:/app/Logs
      - ./appsettings.json:/app/appsettings.json
      - ./cookies.json:/app/cookies.json
    environment:
      # 定时任务
      - Ray_DailyTaskConfig__Cron=0 15 * * *
      - Ray_LiveLotteryTaskConfig__Cron=0 22 * * *
      - Ray_UnfollowBatchedTaskConfig__Cron=0 6 1 * *
      - Ray_VipBigPointConfig__Cron=7 1 * * *
      - Ray_LiveFansMedalTaskConfig__Cron=5 0 * * *
