name: bilibili-daily-task


on:
  
  push: # push触发
    branches: [ main ]
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '5 15 * * *' 
    # cron表达式，时区是UTC时间，比我们早8小时，要用我们的时间减去8小时后填上去，如上所表示的是每天23点5分
    # 建议每个人都修改下时间！不要使用默认时间！最好不要设定在整点，错开峰值，避免大量G站同一个IP在相同时间去请求B站接口，导致IP被禁！
    

jobs:
  run-bilibili-tool:

    runs-on: ubuntu-latest

    steps:

    # 输出IP
    - name: IP
      run: sudo curl ifconfig.me

    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    # 检出
    - name: Checkout
      uses: actions/checkout@v2
      
    # .Net 环境
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # 安装依赖
    - name: Install dependencies
      run: dotnet restore
      
    # 构建应用
    - name: Build APP
      run: dotnet build --configuration Release --no-restore
       
    # 运行
    - name: Run APP
      env:
        Ray_BiliBiliCookie:UserId: ${{secrets.USERID}}
        Ray_BiliBiliCookie:DedeUserID: ${{secrets.DEDEUSERID}} # 为了兼容 GitHub Secrets 经常会被填错
        Ray_BiliBiliCookie:SessData: ${{secrets.SESSDATA}}
        Ray_BiliBiliCookie:BiliJct: ${{secrets.BILIJCT}}
        Ray_BiliBiliCookie:Bili_jct: ${{secrets.BILI_JCT}} # 为了兼容 GitHub Secrets 经常会被填错
        Ray_Push:PushScKey: ${{secrets.PUSHSCKEY}}
        Ray_Security:IsSkipDailyTask: ${{secrets.ISSKIPDAILYTASK}}
        Ray_Security:IntervalSecondsBetweenRequestApi: ${{secrets.INTERVALSECONDSBETWEENREQUESTAPI}}
        Ray_Security:IntervalMethodTypes: ${{secrets.INTERVALMETHODTYPES}}
        Ray_Security:UserAgent: ${{secrets.USERAGENT}}
        Ray_DailyTaskConfig:NumberOfCoins: ${{secrets.NUMBEROFCOINS}}
        Ray_DailyTaskConfig:SelectLike: ${{secrets.SELECTLIKE}}
        Ray_DailyTaskConfig:SupportUpIds: ${{secrets.SUPPORTUPIDS}}
        Ray_DailyTaskConfig:DayOfAutoCharge: ${{secrets.DAYOFAUTOCHARGE}}
        Ray_DailyTaskConfig:DayOfReceiveVipPrivilege: ${{secrets.DAYOFRECEIVEVIPPRIVILEGE}}
        Ray_DailyTaskConfig:DevicePlatform: ${{secrets.DEVICEPLATFORM}}
        Ray_Serilog:WriteTo:0:Args:restrictedToMinimumLevel: ${{secrets.CONSOLELOGLEVEL}}
        Ray_Serilog:WriteTo:0:Args:outputTemplate: ${{secrets.CONSOLELOGTEMPLATE}}
      run: dotnet run -p ./src/Ray.BiliBiliTool.Console -closeConsoleWhenEnd=1 ${{secrets.OTHERCONFIGS}}
