name: bilibili-daily-task


on:
  
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '5 15 * * *' 
    # cron表达式，时区是UTC时间，比我们早8小时，要用我们的时间减去8小时后填上去，如上所表示的是每天23点5分
    # 建议每个人都修改下时间！不要使用默认时间！最好不要设定在整点，错开峰值，避免大量G站同一个IP在相同时间去请求B站接口，导致IP被禁！
    

jobs:
  run-bilibili-tool:

    runs-on: ubuntu-latest

    steps:

    # 输出IP
    - name: IP
      run: sudo curl ifconfig.me

    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    # 检出
    - name: Checkout
      uses: actions/checkout@v2
      
    # .Net 环境
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # 发布
    - name: Publish
      run: |
        cd ./src/Ray.BiliBiliTool.Console
        dotnet publish --configuration Release --self-contained false --output ./bin/Publish/net5-dependent
       
    # 运行
    - name: Run APP
      env:
        ASPNETCORE_ENVIRONMENT: ${{secrets.ENV}} # 运行环境
        Ray_BiliBiliCookie:UserId: ${{secrets.USERID}}
        Ray_BiliBiliCookie:DedeUserID: ${{secrets.DEDEUSERID}} # 为了兼容 GitHub Secrets 经常会被填错
        Ray_BiliBiliCookie:SessData: ${{secrets.SESSDATA}}
        Ray_BiliBiliCookie:BiliJct: ${{secrets.BILIJCT}}
        Ray_BiliBiliCookie:Bili_jct: ${{secrets.BILI_JCT}} # 为了兼容 GitHub Secrets 经常会被填错
        Ray_Serilog:WriteTo:3:Args:botToken: ${{secrets.PUSHTGTOKEN}} # Telegram
        Ray_Serilog:WriteTo:3:Args:chatId: ${{secrets.PUSHTGCHATID}}
        Ray_Serilog:WriteTo:3:Args:containsTrigger: ${{secrets.PUSHTGTRIGGER}}
        Ray_Serilog:WriteTo:4:Args:webHookUrl: ${{secrets.PUSHWEIXINURL}} # 微信
        Ray_Serilog:WriteTo:4:Args:containsTrigger: ${{secrets.PUSHWEIXINTRIGGER}}
        Ray_Serilog:WriteTo:5:Args:webHookUrl: ${{secrets.PUSHDINGURL}} # 钉钉
        Ray_Serilog:WriteTo:5:Args:containsTrigger: ${{secrets.PUSHDINGTRIGGER}}
        Ray_Serilog:WriteTo:6:Args:scKey: ${{secrets.PUSHSCKEY}} # Server酱
        Ray_Serilog:WriteTo:6:Args:containsTrigger: ${{secrets.PUSHSERVERTRIGGER}}
        Ray_Serilog:WriteTo:7:Args:sKey: ${{secrets.PUSHCOOLSKEY}} # 酷推
        Ray_Serilog:WriteTo:7:Args:containsTrigger: ${{secrets.PUSHCOOLTRIGGER}}
        Ray_Serilog:WriteTo:8:Args:api: ${{secrets.PUSHOTHERAPI}} # 自定义api
        Ray_Serilog:WriteTo:8:Args:placeholder: ${{secrets.PUSHOTHERPLACEHOLDER}}
        Ray_Serilog:WriteTo:8:Args:bodyJsonTemplate: ${{secrets.PUSHOTHERBODYJSONTEMPLATE}}
        Ray_Serilog:WriteTo:8:Args:containsTrigger: ${{secrets.PUSHOTHERTRIGGER}}
        Ray_Security:IsSkipDailyTask: ${{secrets.ISSKIPDAILYTASK}}
        Ray_Security:IntervalSecondsBetweenRequestApi: ${{secrets.INTERVALSECONDSBETWEENREQUESTAPI}}
        Ray_Security:IntervalMethodTypes: ${{secrets.INTERVALMETHODTYPES}}
        Ray_Security:UserAgent: ${{secrets.USERAGENT}}
        Ray_Security:WebProxy: ${{secrets.WEBPROXY}}
        Ray_DailyTaskConfig:NumberOfCoins: ${{secrets.NUMBEROFCOINS}}
        Ray_DailyTaskConfig:SelectLike: ${{secrets.SELECTLIKE}}
        Ray_DailyTaskConfig:SupportUpIds: ${{secrets.SUPPORTUPIDS}}
        Ray_DailyTaskConfig:DayOfAutoCharge: ${{secrets.DAYOFAUTOCHARGE}}
        Ray_DailyTaskConfig:AutoChargeUpId: ${{secrets.AUTOCHARGEUPID}}
        Ray_DailyTaskConfig:DayOfReceiveVipPrivilege: ${{secrets.DAYOFRECEIVEVIPPRIVILEGE}}
        Ray_DailyTaskConfig:IsExchangeSilver2Coin: ${{secrets.IsExchangeSilver2Coin}}
        Ray_DailyTaskConfig:DevicePlatform: ${{secrets.DEVICEPLATFORM}}
        Ray_Serilog:WriteTo:0:Args:restrictedToMinimumLevel: ${{secrets.CONSOLELOGLEVEL}}
        Ray_Serilog:WriteTo:0:Args:outputTemplate: ${{secrets.CONSOLELOGTEMPLATE}} 
      run: |
        cd ./src/Ray.BiliBiliTool.Console/bin/Publish/net5-dependent
        dotnet Ray.BiliBiliTool.Console.dll -closeConsoleWhenEnd=1 ${{secrets.OTHERCONFIGS}}
