name: Close Stale Issues
on:
  schedule:
    - cron: "0 8 * * *" # æ¯å¤©çš„ 00:00 è¿è¡Œ
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  close_stale_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues
        uses: actions/stale@v5
        with:
          days-before-stale: 3 # 3 å¤©ä¸æ´»è·ƒåæ ‡è®°Stale
          days-before-close: 3 # æ ‡è®°Staleå3å¤©ä¸æ´»è·ƒåˆ™å…³é—­é—®é¢˜
          stale-issue-label: "Stale" # æ ‡è®°ä¸º "Stale" çš„é—®é¢˜
          stale-issue-message: "ğŸ•¸ï¸ This has been inactive for 3 days, please confirm if it still needs attention~~" # Comment added
          close-issue-message: "ğŸš« This has been inactive for too long and is now closed, feel free to reopen it if needed!" # Comment added
          only-labels: "needs-more-info" # åªå¤„ç†æ ‡ç­¾ä¸º "help wanted" çš„é—®é¢˜
          repo-token: ${{ secrets.GITHUB_TOKEN }}