# 自动同步上游仓库

name: repo-sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1,3,5'
    # UTC时区，比我们东八区早8小时，上面示例为：每周一、三、五的9点。

jobs:
  repo-sync:
    if: ${{ github.repository != 'RayWangQvQ/BiliBiliToolPro' }}

    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/RayWangQvQ/BiliBiliToolPro.git"
          source_branch: "main"
          destination_branch: "main"
          sync_tags: "true"
          github_token: ${{ secrets.PAT }}
